excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Frameworks
- Products
- Targets Support Files
- Finote/Mics/Util/Libraries
# ----- Custom rule -----
disabled_rules: 
   - trailing_whitespace
identifier_name:
  min_length: 2 # only min_length
line_length: 300
